version: "3.9"

services:
  backend:
    build: ./api
    container_name: ecommerce-api
    env_file:
      - ./api/.env
    ports:
      - "3001:3001"  # Only expose for debugging, remove in production
    restart: unless-stopped
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && node src/server.js"

  web:
    build: ./web
    container_name: ecommerce-web
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

  # Optional: Local Postgres for PoC/development
  # For production, use RDS Postgres instead
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password
    ports:
      - "5432:5432"  # Remove in production
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce_user -d ecommerce_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
