version: "3.9"

services:
  backend:
    build: ./api
    container_name: ecommerce-api-prod
    env_file:
      - ./api/.env
    restart: unless-stopped
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && node src/server.js"
    networks:
      - app-network

  web:
    build: ./web
    container_name: ecommerce-web-prod
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  # Optional: Local Postgres for PoC/development
  # For production, use RDS Postgres instead and remove this service
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-postgres-prod
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce_user -d ecommerce_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge